# Generated by Django 4.1.7 on 2023-06-08 10:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gponmap', '0007_qgisline'),
    ]

    operations = [
        migrations.CreateModel(
            name='QgisPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'polygons_all',
                'managed': False,
            },
        ),
    ]
