# Generated by Django 4.1.7 on 2023-06-12 10:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gponmap', '0008_qgispolygon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('capacity', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lines_capacity',
                'managed': False,
            },
        ),
    ]
