# Generated by Django 4.1.7 on 2023-06-13 20:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gponmap', '0010_qgiscoupling_alter_colorline_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='QgisBStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('bstation', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bstations_all',
                'managed': False,
            },
        ),
    ]
