# Generated by Django 4.1.7 on 2023-06-14 20:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gponmap', '0011_qgisbstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='QgisOSB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('osb', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'osb_all',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QgisOSKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('oskm', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'oskm_all',
                'managed': False,
            },
        ),
    ]
